#!/usr/bin/env python
"""
mp4dump fuzzer
"""

MAX_FILESIZE = 32*1024
PROGRAM = 'mp4dump'
MANGLE = "fixed"

from fusil.application import Application
from optparse import OptionGroup
from fusil.process.mangle import MangleProcess
from fusil.process.watch import WatchProcess
from fusil.process.stdout import WatchStdout
from fusil.mangle import MangleFile as MP4Mangle

class Fuzzer(Application):
    NAME = "mp4dump"
    USAGE = "%prog [options] audio.mp4"
    NB_ARGUMENTS = 1

    def createFuzzerOptions(self, parser):
        options = OptionGroup(parser, "mp4dump fuzzer")
        options.add_option("--max-filesize", help="Maximum file size in bytes (default: %s)" % MAX_FILESIZE,
            type="int", default=MAX_FILESIZE)
        return options

    def setupProject(self):
        project = self.project

        orig_filename = self.arguments[0]
        mangle = MP4Mangle(project, orig_filename)
        mangle.max_size = self.options.max_filesize
        mangle.config.min_op = 1
        mangle.config.max_op = 10
        mangle.config.change_size = True

        COMMAND = ['mp4dump', '<mp4dump>']
        process = MangleProcess(project, COMMAND, "<mp4dump>", timeout=60.0)
        process.env.copy('HOME')

        WatchProcess(process, exitcode_score=-0.25)

        stdout = WatchStdout(process)
        stdout.max_nb_line = None
        stdout.show_matching = True
        stdout.addRegex(r"The file may be corrupted", -0.50)

if __name__ == "__main__":
    Fuzzer().main()

